language: go
sudo: true
notifications:
  email: false

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

install:
  - sudo apt-get install -y python-pip
  - sudo pip install cookiecutter
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint

script:
  - cookiecutter --version
  - cookiecutter $TRAVIS_BUILD_DIR --no-input
  - cd app
  - make update
  - git init
  - git add .
  - make
  - ./bin/app version
  - make fmt
  - git diff --name-only | wc -l | xargs test 0 = | git diff --name-only
  - make lint