language: python
sudo: true
go:
  - 1.8.x
  - master
install:
  - sudo apt-get install -y python-pip
  - pip install cookiecutter
script:
  - pwd
  - cookiecutter --version
  - cookiecutter $TRAVIS_BUILD_DIR --no-input